---
- name: Block Start Sound Server (PipeWire)
  when: "'skipped' not in ovos_installer_pipewire_install.keys()"
  block:
    - name: Start PipeWire systemd service
      become: true
      become_user: "{{ ovos_installer_user }}"
      ansible.builtin.systemd_service:
        name: pipewire
        scope: user
        state: started

    - name: Start PulseAudio via PipeWire systemd service
      become: true
      become_user: "{{ ovos_installer_user }}"
      ansible.builtin.systemd_service:
        name: pipewire-pulse
        scope: user
        state: started
      when: ovos_installer_sound_server == 'PulseAudio'

- name: Block Start Sound Server (PulseAudio)
  when: "'skipped' not in ovos_installer_pulseaudio_install.keys()"
  block:
    - name: Start PulseAudio systemd service
      become: true
      become_user: "{{ ovos_installer_user }}"
      ansible.builtin.systemd_service:
        name: pulseaudio
        scope: user
        state: started
