---
- name: Include assert.yml
  ansible.builtin.import_tasks: assert.yml
  tags:
    - always

- name: Include prepare.yml
  ansible.builtin.import_tasks: prepare.yml

- name: Include sanity.yml
  ansible.builtin.import_tasks: sanity.yml

- name: Include firmware.yml
  ansible.builtin.import_tasks: firmware.yml

- name: Include vocalfusion.yml
  ansible.builtin.import_tasks: vocalfusion.yml

- name: Include touchscreen.yml
  ansible.builtin.import_tasks: touchscreen.yml

- name: Include wireplumber.yml
  ansible.builtin.import_tasks: wireplumber.yml
