---
galaxy_info:
  author: GaÃ«tan Trellu (@goldyfruit)
  description: Open Voice OS installer audio tuning
  company: Smart'Gic
  standalone: true
  issue_tracker_url: https://github.com/openvoiceos/ovos-installer/issues
  license: Apache-2.0
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
        - bookworm
        - trixie
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "37"
        - "38"
        - "39"
        - "40"
    - name: ArchLinux
      versions:
        - all
    - name: opensuse
      versions:
        - '15.0'
        - '15.1'
        - '15.2'
        - '15.3'
        - '15.4'
        - '15.5'
        - all
  galaxy_tags:
    - openvoiceos
    - ovos
    - audio
    - tuning

dependencies: []
