---
ovos_sound_pipewire_distributions_skip_alsa:
  - Linux Mint
  - Zorin OS
ovos_sound_pipewire_group_excluded_distributions:
  - Linux Mint
  - Zorin OS
ovos_sound_pipewire_group_excluded_os_families:
  - Suse
  - Archlinux
  - openSUSE Tumbleweed-Slowroll
ovos_sound_pipewire_min_ubuntu_version: "23.04"
ovos_sound_pipewire_min_debian_version: "12.0"
ovos_sound_wsl_default_server: pulseaudio
ovos_sound_detect_default_server: "n/a"
