---
ovos_installer_ovos_docker_repo_url: https://github.com/OpenVoiceOS/ovos-docker.git
ovos_installer_ovos_docker_repo_branch: dev
ovos_installer_hivemind_docker_repo_url: https://github.com/JarbasHiveMind/hivemind-docker.git
ovos_installer_hivemind_docker_repo_branch: feat/initial
ovos_installer_docker_image_tag: "{{ ovos_installer_channel | default('testing') }}"
ovos_installer_docker_pull_policy: always
ovos_installer_docker_compose_remove_orphans: true
ovos_installer_docker_compose_remove_images: all
ovos_installer_docker_compose_remove_volumes: true
ovos_installer_uninstall: "{{ 'present' if (not ovos_installer_cleaning | bool | default(false)) else 'absent' }}"
ovos_installer_venv_python: "3.11"
# ggwave stack doesn't support the ovos-audio >=1.1 move to plugin-manager >=2 yet,
# so limit it to stable/testing on x86_64/aarch64 until an updated release lands.
ovos_installer_enable_ggwave: "{{ (ovos_installer_channel | default('')) in ['stable', 'testing'] and ansible_architecture in ['x86_64', 'aarch64'] }}"
ovos_installer_uv_allow_prerelease: "{{ ansible_facts.python.version.major == 3 and (ansible_facts.python.version.minor | int) >= 13 }}"
ovos_installer_tuning: false
ovos_installer_tuning_performance: >-
  {{ ovos_installer_tuning | bool and (ovos_installer_raspberrypi | default('N/A')) != 'N/A' }}
ovos_installer_tuning_audio_low_latency: "{{ ovos_installer_tuning_performance | bool }}"
ovos_installer_tuning_overclock: "{{ ovos_installer_tuning_performance | bool }}"
ovos_installer_tuning_numa: "{{ ovos_installer_tuning_performance | bool }}"
ovos_installer_systemd_scope: "{{ 'system' if ovos_installer_tuning_performance | bool else 'user' }}"
ovos_installer_overclock_arm_boost: "1"
ovos_installer_overclock_initial_turbo: "60"
ovos_installer_overclock_over_voltage: "6"
ovos_installer_overclock_arm_freq: "{{ '2400' if 'Raspberry Pi 5' in (ovos_installer_raspberrypi | default('')) else '2000' }}"
ovos_installer_overclock_gpu_freq: "750"
