- name: Copy Python requirements.txt files
  ansible.builtin.template:
    src: "{{ item.file }}.j2"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - file: virtualenv/core-requirements.txt
      dest: /tmp/core-requirements.txt
      state: "{{ ovos_installer_profile != 'satellite' and ovos_installer_profile != 'server' }}"
    - file: virtualenv/gui-requirements.txt
      dest: /tmp/gui-requirements.txt
      state: "{{ ovos_installer_feature_gui | bool and ovos_installer_profile != 'satellite' }}"
    - file: virtualenv/skills-requirements.txt
      dest: /tmp/skills-requirements.txt
      state: "{{ ovos_installer_feature_skills | bool and ovos_installer_profile != 'satellite' }}"
    - file: virtualenv/extra-skills-requirements.txt
      dest: /tmp/extra-skills-requirements.txt
      state: "{{ ovos_installer_feature_extra_skills | bool and ovos_installer_profile != 'satellite' }}"
    - file: virtualenv/listener-requirements.txt
      dest: /tmp/listener-requirements.txt
      state: "{{ ovos_installer_profile == 'listener' }}"
    - file: virtualenv/satellite-requirements.txt
      dest: /tmp/satellite-requirements.txt
      state: "{{ ovos_installer_profile == 'satellite' }}"
    - file: virtualenv/server-requirements.txt
      dest: /tmp/server-requirements.txt
      state: "{{ ovos_installer_profile == 'server' }}"
  when: item.state | bool

- name: Create ovos Python venv with tflite_runtime
  moreati.uv.pip:
    name: tflite_runtime
    virtualenv: "{{ ovos_installer_user_home }}/.venvs/ovos"
    virtualenv_command: "{{ ansible_python.executable }} -m venv"
    extra_args: "--trusted-host whl.smartgic.io -f 'https://whl.smartgic.io'"
  when: ovos_installer_cpu_is_capable | bool

- name: Create ovos Python venv without tflite_runtime
  moreati.uv.pip:
    name: wheel
    virtualenv: "{{ ovos_installer_user_home }}/.venvs/ovos"
    virtualenv_command: "{{ ansible_python.executable }} -m venv"
  when: not ovos_installer_cpu_is_capable | bool

- name: Install ggwave Python library
  moreati.uv.pip:
    name: ggwave
    virtualenv: "{{ ovos_installer_user_home }}/.venvs/ovos"
    extra_args: "--trusted-host whl.smartgic.io -f 'https://whl.smartgic.io'"
  when: ovos_installer_enable_ggwave | bool

- name: Install Open Voice OS in Python venv
  vars:
    _ovos_release: "https://raw.githubusercontent.com/OpenVoiceOS/ovos-releases/refs/heads/main/constraints-{{ ovos_installer_channel }}.txt"
    _pip_constraints: "--constraint {{ _ovos_release }}"
    _uv_extra_args: "{{ _pip_constraints }}{{ ' --prerelease=allow' if ovos_installer_uv_allow_prerelease | bool else '' }}"
  moreati.uv.pip:
    requirements: "{{ item.file }}"
    virtualenv: "{{ ovos_installer_user_home }}/.venvs/ovos"
    extra_args: "{{ _uv_extra_args }}"
    state: latest
  register: ovos_installer_install_venv
  until: ovos_installer_install_venv is success
  retries: 5
  delay: 5
  loop:
    - file: /tmp/core-requirements.txt
      state: "{{ ovos_installer_profile != 'satellite' and ovos_installer_profile != 'server' }}"
    - file: /tmp/gui-requirements.txt
      state: "{{ ovos_installer_feature_gui | bool and ovos_installer_profile != 'satellite' }}"
    - file: /tmp/skills-requirements.txt
      state: "{{ ovos_installer_feature_skills | bool and ovos_installer_profile != 'satellite' }}"
    - file: /tmp/extra-skills-requirements.txt
      state: "{{ ovos_installer_feature_extra_skills | bool and ovos_installer_profile != 'satellite' }}"
    - file: /tmp/listener-requirements.txt
      state: "{{ ovos_installer_profile == 'listener' }}"
    - file: /tmp/satellite-requirements.txt
      state: "{{ ovos_installer_profile == 'satellite' }}"
    - file: /tmp/server-requirements.txt
      state: "{{ ovos_installer_profile == 'server' }}"
  when: item.state | bool

- name: Ensure numpy==1.26.4 Python library is installed
  moreati.uv.pip:
    name: numpy==1.26.4
    virtualenv: "{{ ovos_installer_user_home }}/.venvs/ovos"
    state: present

- name: Change files ownership of ovos virtualenv
  ansible.builtin.command:
    cmd: |
      chown -R {{ ovos_installer_user }}:{{ ovos_installer_group }} {{ ovos_installer_user_home }}/.venvs/ovos
  changed_when: false

- name: Add VIRTUAL_ENV variable to .bashrc and update user PATH
  vars:
    _path: "{{ ovos_installer_user_home }}/.venvs/ovos/bin"
  ansible.builtin.lineinfile:
    path: "{{ ovos_installer_user_home }}/.bashrc"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    owner: "{{ ovos_installer_user }}"
    group: "{{ ovos_installer_group }}"
    mode: "0644"
    state: "{{ ovos_installer_uninstall }}"
  loop:
    - {"line": "VIRTUAL_ENV={{ _path }}", "regexp": "^VIRTUAL_ENV"}
    - {"line": "PATH=$PATH:{{ _path }}", "regexp": "^PATH"}
  when: ovos_installer_i2c_devices | from_json | length < 1
  tags:
    - always

- name: Add auto Python virtualenv loading on auto-detected devices
  ansible.builtin.lineinfile:
    path: "{{ ovos_installer_user_home }}/.bashrc"
    line: "source {{ ovos_installer_user_home }}/.venvs/ovos/bin/activate"
    regexp: "^source {{ ovos_installer_user_home }}/.venvs/ovos/bin/activate"
    owner: "{{ ovos_installer_user }}"
    group: "{{ ovos_installer_group }}"
    mode: "0644"
    state: "{{ ovos_installer_uninstall }}"
  when: ovos_installer_i2c_devices | from_json | length >= 1
  tags:
    - always

- name: Generate _identity.json
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.shell:
    cmd: |
      hivemind-client set-identity \
        --key {{ ovos_installer_satellite_key }} \
        --password {{ ovos_installer_satellite_password }} \
        --host {{ ovos_installer_listener_host }} \
        --port {{ ovos_installer_listener_port | default(5678) }} \
        --siteid {{ ovos_installer_site_id | default("voice-sat-1") }}
    executable: /bin/bash
  environment:
    PATH: "{{ ovos_installer_user_home }}/.venvs/ovos/bin"
    VIRTUAL_ENV: "{{ ovos_installer_user_home }}/.venvs/ovos"
  changed_when: false
  when: ovos_installer_profile == "satellite"

- name: Run ovos-config for auto-configuration of STT and TTS based on language
  vars:
    _ovos_config_tts_gender: "{{ '--female' if ovos_installer_locale in ['eu-ES', 'gl-ES'] else '--male' }}"
  become: true
  become_user: "{{ ovos_installer_user }}"
  ansible.builtin.shell:
    cmd: |
      ovos-config autoconfigure --lang {{ ovos_installer_locale }} {{ _ovos_config_tts_gender }}
    executable: /bin/bash
  environment:
    PATH: "{{ ovos_installer_user_home }}/.venvs/ovos/bin"
    VIRTUAL_ENV: "{{ ovos_installer_user_home }}/.venvs/ovos"
  changed_when: false
  when: ovos_installer_profile != "server"

- name: Remove ovos Python virtualenv and requirements.txt files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ ovos_installer_user_home }}/.venvs/ovos"
    - /tmp/core-requirements.txt
    - /tmp/gui-requirements.txt
    - /tmp/skills-requirements.txt
    - /tmp/extra-skills-requirements.txt
    - /tmp/listener-requirements.txt
    - /tmp/satellite-requirements.txt
    - /tmp/server-requirements.txt
    - /opt/mark1
    - /opt/sj201
    - "{{ ovos_installer_user_home }}/.local/bin/ovos-messagebus"
  when: ovos_installer_cleaning | bool
  tags:
    - uninstall
