---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 5.0.4
  - name: community.general
    version: 10.7.6
  - name: kewlfft.aur
    version: 0.11.1
  - name: moreati.uv
    version: 0.0.3
