---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.7
  - name: community.general
    version: 12.3.0
  - name: kewlfft.aur
    version: 0.13.0
  - name: moreati.uv
    version: 0.0.3
