---
- name: Download and extract Rust messagebus
  ansible.builtin.unarchive:
    src: "{{ ovos_virtualenv_rust_messagebus_archive_url }}"
    dest: "{{ ovos_installer_user_home }}/.local/bin"
    mode: "0755"
    owner: "{{ ovos_installer_user }}"
    group: "{{ ovos_installer_group }}"
    remote_src: true
  register: ovos_virtualenv_rust_messagebus_unarchive
  retries: 3
  delay: 3
  until: ovos_virtualenv_rust_messagebus_unarchive is succeeded
